"""empty message

Revision ID: d880203fe154
Revises: 88435241f9f2
Create Date: 2024-06-06 11:39:36.258587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd880203fe154'
down_revision: Union[str, None] = '88435241f9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'user_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'user_id', server_default=1)
    # ### end Alembic commands ###
